plugins {
    id 'groovy'
    id 'java-gradle-plugin'
}

repositories {
    mavenCentral()
}

configurations {
    testPluginClasspath
}

gradlePlugin {
    testSourceSets(sourceSets.test)
    plugins {
        buildIntelligence {
            id = 'com.fizzpod.build-intelligence'
            implementationClass = 'com.fizzpod.buildintelligence.BuildIntelligencePlugin'
        }
    }
}

tasks.named('pluginUnderTestMetadata') {
    pluginClasspath.from(configurations.testPluginClasspath)
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    testImplementation 'org.spockframework:spock-core:2.4-groovy-4.0'
    testImplementation 'org.junit.platform:junit-platform-launcher'
    testImplementation project(':sample-provider')
    testPluginClasspath project(':sample-provider')
}

test {
    useJUnitPlatform()
}
